- .travis.yml
- src/ColorVectorSpace.jl
And enable 0.3 and 0.4 on travis
> Union() -> Union{}

- src/ColorVectorSpace.jl
- test/runtests.jl
`var` now works on arrays of `Gray`s
> added var() on Gray

- src/ColorVectorSpace.jl
These generate warnings on julia-0.5
> Remove duplicated methods

- src/ColorVectorSpace.jl
- test/runtests.jl
I've found this useful for tests.
> Extend norm and isapprox

- appveyor.yml
Ref https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/53/files/d58f05169c0de3bc3e0210249c7afdf3e155cea1#r78301105, CC @tkelman.
> Fix appveyor links

- src/ColorVectorSpace.jl
- test/runtests.jl
More issues discovered by ImageMetadata. This one only causes a problem on julia-0.6 for some reason.
> Fix and test division by BitArray

- test/REQUIRE
- test/runtests.jl
> replace FactCheck by TestSets

- src/ColorVectorSpace.jl
> Remove Base.ShortCircuiting since it was removed from Base

- src/ColorVectorSpace.jl
- test/REQUIRE
- test/runtests.jl
`quantile` doesn't work without `float`.  not sure what else might depend on it.
> support quantile for Gray

- REQUIRE
- src/ColorVectorSpace.jl
fixes hard crash on import on julia master
> update histrange with move from Base -> StatsBase

- src/ColorVectorSpace.jl
- test/runtests.jl
This requires https://github.com/JuliaGraphics/ColorTypes.jl/pull/72. Not sure what's the policy applying to merging coupled PR's here.
> Fix #67 and tests depwarn/errors

- src/ColorVectorSpace.jl
Fix for https://github.com/JuliaLang/julia/pull/21328
> Eliminate specialization for broadcast on 0.6

- src/ColorVectorSpace.jl
The latest Compat issues a depwarn.
> Remove atsign-functorize

- src/ColorVectorSpace.jl
> Deprecate elementwise operations in favor of broadcasting

- Project.toml
- REQUIRE
- test/REQUIRE
Looks like we haven't had a release in a while. This bumps the version to 0.7 and switches to the new registration system.
> Add Project file and remove REQUIRE

- Project.toml
- test/runtests.jl
This requires a change in tolerance for one test.
Closes #114
> Bump compatibility for Colors and FixedPointNumbers

- Project.toml
> Compat: ColorTypes 0.9, Colors 0.11

- src/ColorVectorSpace.jl
- test/runtests.jl
> Fix arithmetic on nonparametric types 

- src/ColorVectorSpace.jl
> Remove unneded gray method

- README.md
- src/ColorVectorSpace.jl
- test/runtests.jl
> Implement promotion in multiplication

- Project.toml
- src/ColorVectorSpace.jl
- test/runtests.jl
xref https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/106#issuecomment-790484474
> Fix SpecialFunctions depwarns

- Project.toml
- src/ColorVectorSpace.jl
> Fix warning for importing `Statistics._mean_promote`

- src/ColorVectorSpace.jl
- test/runtests.jl
This adds the 2-arg `show`. The output of 2-arg `show` does not include newlines and can be parsed.
This also makes it possible to construct `RGBRGB` from an `AbstractMatrix`.
This is a breaking change, but I am not sure whether this can be in the v0.9 series.
```julia
julia> show(stdout, RGBRGB{Float32}(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9))
RGBRGB{Float32}(
0.1f0  0.4f0  0.7f0
0.2f0  0.5f0  0.8f0
0.3f0  0.6f0  0.9f0)
julia> RGBRGB{Float32}(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
RGBRGB{Float32}(
0.1f0  0.4f0  0.7f0
0.2f0  0.5f0  0.8f0
0.3f0  0.6f0  0.9f0)
```
```julia
julia> show(stdout, RGBRGB{Float32}(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9))
RGBRGB{Float32}([0.1 0.4 0.7; 0.2 0.5 0.8; 0.3 0.6 0.9])
julia> RGBRGB{Float32}(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9) …
```
> Make `RGBRGB` display consistent with `Matrix`

- README.md
I was going to add error hints for unsupported multiplications and update the README. However, the situation is more troublesome than I thought :sweat_smile:, so I'll make some separate PRs.
> Update `RGBRGB` output in README.md

- src/ColorVectorSpace.jl
- test/runtests.jl
> Add support for `hadamard`(`⊙`) for `TransparentGray`/`TransparentRGB`

- Project.toml
The previous commit had failed to `rebase`. :sob: Sorry for messing up the log.
> Version 0.9.4 (REDO)

- src/ColorVectorSpace.jl
- test/runtests.jl
This also fixes a broken scaling with `Normed`.
```julia
julia> 0.6N0f8 * RGB{N0f16}(0.2)
RGB{N0f16}(0.00047,0.00047,0.00047) # master
RGB{N0f16}(0.12,0.12,0.12)          # this PR
```
Note that the result of the `N0f16` operation will be slightly different due to rounding errors.
```julia
julia> 0.72992N0f16 * Gray(0.72992N0f16)
Gray{N0f16}(0.53278) # master
Gray{N0f16}(0.53277) # this PR
```
In some cases, `master` is theoretically more efficient, but the benchmarks showed little effect. For this reason, I simplified some specialized methods. Also, this does not optimize `⊗` for RGBs.
Fixes #166
> Optimize multiplication operations

- .github/workflows/UnitTest.yml
- Project.toml
- README.md
- src/ColorVectorSpace.jl
- test/runtests.jl
A slight addition to #187, CC @t-bltg
> Breaking abs2, tweaked
