JuliaGraphics/ColorVectorSpace.jl

.travis.yml
REQUIRE
src/ColorVectorSpace.jl
test/runtests.jl

Incorporate and fix deprecations caused by the wonderful https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/27. This also commits to julia 0.4 and deletes cruft.
This won't pass tests until https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/31 gets tagged. I'll re-run the travis jobs when that happens, but submitting for comments.

UFixed transition and commit to julia 0.4

---

src/ColorVectorSpace.jl

Overall these just seem like missing methods, so this is an improvement in any case.
There are a number of deprecations to fix, but we need to wait for Compat to update.

Fix arithmetic operations on julia-0.5

---

.travis.yml
src/ColorVectorSpace.jl
test/runtests.jl

`nan` is much like `zero` and `one`. Julia used to have a `nan` function but it got deprecated for `convert(T, NaN)` instead. However, in general it shouldn't be possible to convert a real number to an `RGB`, so I think we need to (re)introduce the `nan` function here.

Implement nan(RGB{Float32}) etc.

---

REQUIRE
appveyor.yml
src/ColorVectorSpace.jl

Requires JuliaLang/Compat.jl#280 and a new `Compat` tag.

Fix depwarn on 0.6 due to vectorized functions

---

src/ColorVectorSpace.jl

No longer did this prevent an ambiguity warning: on Julia 0.6, this *causes* an ambiguity warning.

Delete ambiguous method

---

src/ColorVectorSpace.jl
test/REQUIRE
test/runtests.jl

This implements the "dot product" for Gray & RGB colors. Gray is obviously straightforward; for RGB, it's a little more subtle because we want `x = RGB(g, g, g)` (which can be thought of as a grayscale color since all colorchannels are identical) to yield the same value for both `dotc(x, x)` and `y = Gray(x); dotc(y, y)`. As a consequence, we weight the color channels in the manner consistent with conversion to rec601 luma.

Add dotc, for taking the grayscale-normalized dot product across color channels

---

src/ColorVectorSpace.jl
test/runtests.jl

For types that can't handle Inf, this seems important when inlining is off. (Dependence on inlining is weird, but I didn't really try to track it down.)
With the test added here (but omitting the specialized `promote_op` method), when inlining is off you get this error:
```jl
Expression: acu ./ trues(1) --> acu
ArgumentError: FixedPointNumbers.UFixed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent Inf
in throw_converterror(::Type{FixedPointNumbers.UFixed{UInt8,8}}, ::Float32) at /home/tim/.julia/v0.5/FixedPointNumbers/src/FixedPointNumbers.jl:126
in _convert(::Type{FixedPointNumbers.UFixed{UInt8,8}}, ::Type{UInt8}, ::Float32) at /home/tim/.julia/v0.5/FixedPointNumbers/src/ufixed.jl:55
in convert(::Type{FixedPointNumbers.UFixed{UInt8,8}}, ::Float32) at …
```

Fix promote_op for division

---

REQUIRE
src/ColorVectorSpace.jl
test/REQUIRE
test/runtests.jl

For good measure, to help with the move of `zero` and `one` in #68 I threw in a dependency on ColorTypes 0.3.3 (which was not tagged when that PR was submitted).

Support +/- for mixtures of RGB and Gray

---

src/ColorVectorSpace.jl
test/runtests.jl

see discussion [here](https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/44#issuecomment-258507920)

added typemin/max for AbstractGray

---

src/ColorVectorSpace.jl
src/dots.jl
test/runtests.jl

This is a breaking change, because on Julia 0.6 the array eltype no longer "wins": the output is the same as what you'd get from adding the scalars. The package's behavior is now consistent with whatever the Julia version does for other "number" types.

Use broadcast rules on 0.6 (fixes dot-operators depwarn)

---

REQUIRE
src/ColorVectorSpace.jl
test/runtests.jl

There are more functions that could be converted to using `reducec` or `mapreducec`, but this is a start. Supersedes #72.

Use mapreducec for implementation of isfinite, isnan, isinf

---

src/ColorVectorSpace.jl

Use right-closed histograms when overloading histrange

---

src/ColorVectorSpace.jl

Addresses #85 and an apparent dispatch ambiguity.
Should bring package up to v0.7-beta, modulo deprecations.

more fixes for Julia v0.7

---

src/ColorVectorSpace.jl

Another instance of duplicate types.
Depends on https://github.com/JuliaGraphics/ColorTypes.jl/pull/111

Eliminate duplicate types already defined in ColorTypes.jl

---

src/ColorVectorSpace.jl
test/runtests.jl

Fix deprecation warning in Julia v0.7.
Do you suggest some test to cover this function? It is currently uncovered by the test suite.

Rename atan2 to atan in Julia v0.7 and beyond

---

.travis.yml
appveyor.yml
test/runtests.jl

I was fooled by not being on `dev` in #98.
Also noticed we need to expand the testing matrix.

Remove tests for deprecated functionality

---

Project.toml
src/ColorVectorSpace.jl
test/runtests.jl

Fixes https://github.com/JuliaGraphics/Colors.jl/issues/326

Fix inference of mapreduce

---

.travis.yml
Project.toml
appveyor.yml

Since many packages didn't have upper bounds, it would have blocked future automated merging of registration requests.

Refine the compat section

---

src/ColorVectorSpace.jl
src/precompile.jl

This adds some precompile statements to reduce latency. Because the methods are simple to infer, the savings are modest, but combined with precompiles in other packages (FixedPointNumbers, ColorTypes, Colors) I'm getting latency reductions of ~30% for some common operations. So these seem worth having.

Add some precompiles

---

Project.toml
src/ColorVectorSpace.jl

This is a minimal update that gets this working with the latest versions of FixedPointNumbers, ColorTypes, and Colors. I've checked that tests pass without warnings on both ColorTypes 0.9 and ColorTypes 0.10.
Closes #122 
Closes #127
Closes #128

Bump compatibility for FPN/ColorTypes/Colors

---

src/ColorVectorSpace.jl
test/runtests.jl

I think we've decided that depwarns aren't breaking, so before #131 lands let's deprecate StatsBase. Given that we now have strong [compat] bounds and we've been encouraging people to shift away from `imhist` for a long time, perhaps we don't need to leave that deprecation in place for very long.
This also marks one test as broken, ref #134.

Deprecate StatsBase

---

Project.toml
README.md
src/ColorVectorSpace.jl
test/runtests.jl

This notably defines 3 multiplication operators for RGB colors. It also un-defines `abs2`, because how that should work is a bit ambiguous. Finally, it defines a new `varmult` function, which allows one to compute variance using a specific multiplication operator.
Fixes #126. Requires the following:

Redesign color arithmetic

---

src/ColorVectorSpace.jl
test/runtests.jl

This is the part of PR #125 about `complement`. (cf. https://github.com/JuliaImages/Images.jl/issues/698, https://github.com/JuliaImages/Images.jl/pull/879)
The differences from the original are as follows:
- This exports `complement` (as suggested in https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/125#discussion_r389335911).
- This drops the deprecation for array input.
- It is the responsibility of Images.jl.
- This modifies the test.
Images.jl does not yet support ColorVectorSpace v0.9, so it is possible to include this in v0.9, but I don't think that would be a good idea.
Also, `oneunit(::AbstractGray)` has been missing. :confused: This may be fixed in ColorTypes v0.11.
cc: @wizofe

Add `complement` migrated from Images.jl

---

src/ColorVectorSpace.jl
test/runtests.jl

This should not be a breaking change. (Oh, I thought I had created this branch on my fork. Sorry.)
Closes #146.

Generalize non-parametric type handling

---

src/ColorVectorSpace.jl
test/runtests.jl

This was written with care so as not to change the behavior, but I think it needs further review.
```julia
julia> -Gray(true)
ERROR: InexactError: Bool(-1) # master
Gray{Bool}(true) # this PR
```
Closes #124 (completely removed)

Clean up verbose or old-style definitions

---

Project.toml
src/ColorVectorSpace.jl
test/runtests.jl

This also prepares for future migration of `nan` to ColorTypes. (cf. https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/75#issuecomment-824011878)

Version 0.9.3

---

README.md
src/ColorVectorSpace.jl

This also adds the note for `abs`/`abs2` into README.md.
If necessary, I will write the tests for error hints.

Add error hints for unsuported operations

---

src/ColorVectorSpace.jl
test/runtests.jl

This uses the promotion rules defined in ColorTypes.jl v0.10 or later.
This PR shouldn't affect the "working" codes, but it does change a specification which has been unchanged for many years, so I will wait a little while before merging it.
Closes #155

[RFC] Add more support for color type promotions

---

src/ColorVectorSpace.jl
test/runtests.jl

This also removes some of the optimization using the reciprocals.
```julia
julia> Gray(reinterpret(N0f8, 0x5)) / reinterpret(N0f8, 0x6)
Gray{N0f8}(0.831)     # this PR
ERROR: ArgumentError: # v0.9.4
julia> RGB(reinterpret(N0f8, 0x5)) / reinterpret(N0f8, 0x6)
RGB{N0f8}(0.831,0.831,0.831) # this PR
RGB{N0f8}(0.835,0.835,0.835) # v0.9.4
julia> Gray(eps(N0f8)) / 3.0f0
Gray{Float32}(0.0013071896f0) # this PR
Gray{Float32}(0.0013071897f0) # v0.9.4
```
In the case of `RGB{N0f8}`, the absolute error does not change, but the round-to-even  is applied in this PR.
Fixes #154

Fix overflow errors in division by `Normed`/`Fixed`

---

src/ColorVectorSpace.jl
test/runtests.jl

~I'm going to create some separate PRs for the parts not related to `Bool`.~
This PR only fixes return types which are clearly unreasonable. Other inconsistent return types are leaved for backward compatibility for now.
~I feel the need to make the code more generalized before we can achieve v1.0. However, I am not sure when to do that. (**Edit:** see #156)~
Mostly improved.

[RFC] Improve consistency of arithmetic with `Bool`

---

.github/workflows/UnitTest.yml

* remove cron jobs so that Github Action doesn't automatically disable our unit test CI after 60 days of inactivity
* add one x86 test target
* only test windows and macOS target with Julia 1 to reduce CI credits

update unit test configuration

---

src/ColorVectorSpace.jl
test/runtests.jl

Somewhat disturbingly, while `HSV` was not a subtype of `MathTypes`,
`AHSV` was. This mostly fixes the definition.
For a really, really good type hierarchy, we'll have to redesign
ColorTypes to enforce `C<:Color{T,N}`, e.g.
```
abstract type TransparentColor{T,N,M,C<:Color{T,M}} end
```
and then somehow link `M` to `N-1`. We can do that for specific cases
(e.g., AbstractRGB) but probably not in general.

Fix the definition of MathTypes

---

src/ColorVectorSpace.jl
test/runtests.jl

This is the complement to `varmult`. Useful for finishing
https://github.com/JuliaImages/Images.jl/pull/971

Add `stdmult`

---

src/ColorVectorSpace.jl
test/runtests.jl

Formerly, `sum(Gray[true, true])` triggered an error
```julia
ERROR: ArgumentError: 2 is an integer in the range 0-255, but integer inputs are encoded with the N0f8
type, an 8-bit type representing 256 discrete values between 0 and 1.
Consider dividing your input values by 255, for example: Gray{N0f8}(2/255)
Or use `reinterpret(N0f8, x)` if `x` is a `UInt8`.
See the READMEs for FixedPointNumbers and ColorTypes for more information.
```

Support reductions with `Gray{Bool}`

---

README.md
src/ColorVectorSpace.jl
test/runtests.jl

`abs2` was removed in #131 out of concerns about mathematical consistency. This brings it back in a way that's now consistent, but I think with different numeric values than previously. Even though ColorVectorSpace 0.9 has not yet bubbled up to the top of the JuliaImages stack, it may be time to consider restoring it.
Fixes #157.

Implement `abs2`

---

Project.toml
README.md
src/ColorVectorSpace.jl

This is part of the plan for changing the value returned by `abs2`.
This stage is designed to catch user-level scripts which may not
run with `--depwarn=yes`.

Transition to noisy depwarn for `abs2`

---

src/ColorVectorSpace.jl
test/runtests.jl

When called with explicit type we should return a result of that type.
Discussion for this is in JuliaGraphics/ColorTypes.jl/issues/123.
This breaks existing behaviour as per #131 and #126.
For example, `floor(Int, Gray(x))` should return an Int and the result should be the same as `floor(Int, x)`, treating `Gray`s as numbers.

Math operations with explicit types

---

Project.toml
ext/SpecialFunctionsExt.jl
src/ColorVectorSpace.jl
test/runtests.jl

Fix https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/184.
Fix https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/182.
Fix last part of https://github.com/JuliaPlots/UnicodePlots.jl/issues/291.
This is a proposal to make all the `SpecialFunctions` related functions (which are clearly piracy) optional using weak dependencies on `julia` >= 1.9 and `Requires` on older releases.
This would be (slightly) breaking so I guess we should bump `ColorVectorSpace` to `0.10.0` if this PR is merged, since you'd have to use:
```julia
julia> using SpecialFunctions
julia> using ColorVectorSpace
```
to recover all the functionalities on current master.
Note that `lfact` is renamed to `logfactorial` since `lfact` was deprecated in `SpecialFunctions`.
I followed the guidelines in …

conditionally use `SpecialFunctions` through weak deps or `Requires`
